## pandas筛选数据的15个常用技巧，主要包括5个知识点：

- 比较运算：`==、<、>、>=、<=、!=`
- 范围运算：`between(left,right)`
- 字符筛选:`str.contains(pattern或字符串,na=False)`
- 逻辑运算：`&（与）、|（或）、not(取反)`
- 比较函数：`eq, ne, le, lt, ge, gt（相当于==,=!，<=，<，>=，>）`
- `apply`和`isin`函数

In [2]:
import pandas as pd
data=pd.read_excel('data/超市运营数据模板.xlsx')
data.columns

Index(['商品ID', '类别ID', '门店编号', '单价', '销量', '订单ID', '日期', '时间'], dtype='object')

## 1.筛选门店编号为'CDXL'的运营数据
### ①第一种方法，用比较运算符‘==’：

In [3]:
data[data.门店编号=='CDXL']

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
2330,29989083,922000000,CDXL,4.20,0.742,20201003CDLG000410056442,2017-05-21,09:05
2331,29989061,922000000,CDXL,5.62,0.100,20201003CDLG000410056442,2017-05-22,09:05
2332,29989063,922000000,CDXL,6.80,0.390,20201003CDLG000410056442,2017-05-23,09:05
2333,30006700,915020002,CDXL,6.12,1.000,20201003CDLG000410056442,2017-05-24,09:05
2334,30214809,925090000,CDXL,31.42,2.832,20201003CDLG000410056442,2017-05-25,09:05
...,...,...,...,...,...,...,...,...
3473,30031870,915030401,CDXL,6.58,0.862,20201003CDLG000510025147,2020-07-07,10:59
3474,30008276,911010501,CDXL,15.42,0.481,20201003CDLG000510025148,2020-07-08,11:00
3475,30033854,910000000,CDXL,9.62,1.000,20201003CDLG000510025149,2020-07-09,11:17
3476,30206214,910000000,CDXL,15.62,1.000,20201003CDLG000510025150,2020-07-10,11:40
3477,30129510,925090000,CDXL,23.21,0.312,20201003CDLG000510025151,2020-07-11,11:50

## ②第二种方法，用比较函数'eq'：

In [5]:
data[data['门店编号'].eq('CDXL')]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
2330,29989083,922000000,CDXL,4.20,0.742,20201003CDLG000410056442,2017-05-21,09:05
2331,29989061,922000000,CDXL,5.62,0.100,20201003CDLG000410056442,2017-05-22,09:05
2332,29989063,922000000,CDXL,6.80,0.390,20201003CDLG000410056442,2017-05-23,09:05
2333,30006700,915020002,CDXL,6.12,1.000,20201003CDLG000410056442,2017-05-24,09:05
2334,30214809,925090000,CDXL,31.42,2.832,20201003CDLG000410056442,2017-05-25,09:05
...,...,...,...,...,...,...,...,...
3473,30031870,915030401,CDXL,6.58,0.862,20201003CDLG000510025147,2020-07-07,10:59
3474,30008276,911010501,CDXL,15.42,0.481,20201003CDLG000510025148,2020-07-08,11:00
3475,30033854,910000000,CDXL,9.62,1.000,20201003CDLG000510025149,2020-07-09,11:17
3476,30206214,910000000,CDXL,15.62,1.000,20201003CDLG000510025150,2020-07-10,11:40
3477,30129510,925090000,CDXL,23.21,0.312,20201003CDLG000510025151,2020-07-11,11:50

## 2.筛选单价小于等于10元的运营数据
### ③第一种方法，用比较运算符‘<=’:

In [6]:
data[data.单价<=10]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
5,30022232,960000000,CDNL,0.30,1.000,20201003CDLG000210052759,2011-01-08,09:56
9,29989059,922000003,CDNL,1.98,1.212,20201003CDLG000210052759,2011-01-12,09:56
11,30006343,915030400,CDNL,3.98,2.294,20201003CDLG000210052760,2011-01-14,09:57
...,...,...,...,...,...,...,...,...
3466,30006040,915010000,CDXL,9.57,0.894,20201003CDLG000510025144,2020-06-30,10:35
3469,30005192,914010000,CDXL,9.52,1.000,20201003CDLG000510025146,2020-07-03,10:58
3470,30023041,923000006,CDXL,3.20,1.620,20201003CDLG000510025146,2020-07-04,10:58
3473,30031870,915030401,CDXL,6.58,0.862,20201003CDLG000510025147,2020-07-07,10:59
3475,30033854,910000000,CDXL,9.62,1.000,20201003CDLG000510025149,2020-07-09,11:17

### ④第二种方法，用比较函数'le'：

In [7]:
data[data['单价'].le(10)]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
5,30022232,960000000,CDNL,0.30,1.000,20201003CDLG000210052759,2011-01-08,09:56
9,29989059,922000003,CDNL,1.98,1.212,20201003CDLG000210052759,2011-01-12,09:56
11,30006343,915030400,CDNL,3.98,2.294,20201003CDLG000210052760,2011-01-14,09:57
...,...,...,...,...,...,...,...,...
3466,30006040,915010000,CDXL,9.57,0.894,20201003CDLG000510025144,2020-06-30,10:35
3469,30005192,914010000,CDXL,9.52,1.000,20201003CDLG000510025146,2020-07-03,10:58
3470,30023041,923000006,CDXL,3.20,1.620,20201003CDLG000510025146,2020-07-04,10:58
3473,30031870,915030401,CDXL,6.58,0.862,20201003CDLG000510025147,2020-07-07,10:59
3475,30033854,910000000,CDXL,9.62,1.000,20201003CDLG000510025149,2020-07-09,11:17

## 3.筛选销量大于2000的运营数据
### ⑤第一种方法，用比较运算符‘>=’:

In [8]:
data[data.销量>2]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
11,30006343,915030400,CDNL,3.98,2.294,20201003CDLG000210052760,2011-01-14,09:57
13,30031870,915030401,CDNL,8.17,2.138,20201003CDLG000210052760,2011-01-16,09:57
22,30026255,915030104,CDNL,3.32,2.868,20201003CDLG000210052762,2011-01-25,10:00
47,30020145,915030104,CDNL,4.16,2.982,20201003CDLG000210052772,2011-02-19,10:11
...,...,...,...,...,...,...,...,...
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3444,29989085,922000002,CDXL,1.18,2.373,20201003CDLG000510025138,2020-06-08,09:37
3456,30203637,923000006,CDXL,3.20,2.318,20201003CDLG000510025140,2020-06-20,09:41
3462,30214814,925090000,CDXL,33.42,2.090,20201003CDLG000510025143,2020-06-26,10:34

In [10]:
### ⑥第二种方法，用比较函数'ge'：
data[data['销量'].ge(2)]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
11,30006343,915030400,CDNL,3.98,2.294,20201003CDLG000210052760,2011-01-14,09:57
13,30031870,915030401,CDNL,8.17,2.138,20201003CDLG000210052760,2011-01-16,09:57
22,30026255,915030104,CDNL,3.32,2.868,20201003CDLG000210052762,2011-01-25,10:00
...,...,...,...,...,...,...,...,...
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3444,29989085,922000002,CDXL,1.18,2.373,20201003CDLG000510025138,2020-06-08,09:37
3456,30203637,923000006,CDXL,3.20,2.318,20201003CDLG000510025140,2020-06-20,09:41
3461,30026026,935010702,CDXL,2.50,2.000,20201003CDLG000510025141,2020-06-25,09:47
3462,30214814,925090000,CDXL,33.42,2.090,20201003CDLG000510025143,2020-06-26,10:34

## 4.筛选除门店'CDXL'外的运营数据
### ⑦第一种方法，用比较运算符‘!=’:

In [11]:
data[data.门店编号!='CDXL']

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
0,30006206,915000003,CDNL,25.23,0.328,20201003CDLG000210052759,2011-01-03,09:56
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
2,30200518,922000000,CDNL,19.62,0.230,20201003CDLG000210052759,2011-01-05,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
4,30179558,915000100,CDNL,47.41,0.226,20201003CDLG000210052759,2011-01-07,09:56
...,...,...,...,...,...,...,...,...
2325,30031870,915030401,CDLG,6.58,0.862,20201003CDLG000410056440,2017-05-16,09:03
2326,30006039,915010001,CDLG,11.58,1.238,20201003CDLG000410056440,2017-05-17,09:03
2327,30022233,960000000,CDLG,0.20,1.000,20201003CDLG000410056440,2017-05-18,09:03
2328,29989058,922000001,CDLG,1.98,1.737,20201003CDLG000410056441,2017-05-19,09:05
2329,29989059,922000003,CDLG,1.98,2.929,20201003CDLG000410056441,2017-05-20,09:05

### ⑧第二种方法，用比较函数'ne':

In [12]:
data[data['门店编号'].ne('CDXL')]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
0,30006206,915000003,CDNL,25.23,0.328,20201003CDLG000210052759,2011-01-03,09:56
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
2,30200518,922000000,CDNL,19.62,0.230,20201003CDLG000210052759,2011-01-05,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
4,30179558,915000100,CDNL,47.41,0.226,20201003CDLG000210052759,2011-01-07,09:56
...,...,...,...,...,...,...,...,...
2325,30031870,915030401,CDLG,6.58,0.862,20201003CDLG000410056440,2017-05-16,09:03
2326,30006039,915010001,CDLG,11.58,1.238,20201003CDLG000410056440,2017-05-17,09:03
2327,30022233,960000000,CDLG,0.20,1.000,20201003CDLG000410056440,2017-05-18,09:03
2328,29989058,922000001,CDLG,1.98,1.737,20201003CDLG000410056441,2017-05-19,09:05
2329,29989059,922000003,CDLG,1.98,2.929,20201003CDLG000410056441,2017-05-20,09:05

## 5.筛选2020年5月的运营数据
首先将日期格式化：

In [13]:
data['日期']=data["日期"].values.astype('datetime64')  #如果已为日期格式则此步骤可省略
data['日期']
import datetime
s_date = datetime.datetime.strptime('2020-04-30', '%Y-%m-%d').date()  #起始日期
e_date = datetime.datetime.strptime('2020-06-01', '%Y-%m-%d').date()  #结束日期

### ⑨第一种方法，用逻辑运算符号'>' '<'和'&'：
Pandasdatetime64[ns]不能直接与datetime.date相比，需要用pd.Timestamp进行转化

In [14]:
data[(data.日期>pd.Timestamp(s_date))&(data.日期<pd.Timestamp(e_date))]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
3406,30026255,915030104,CDXL,4.00,20.000,20201003CDLG000510025122,2020-05-01,08:58
3407,29989072,922000002,CDXL,0.78,0.769,20201003CDLG000510025123,2020-05-02,09:01
3408,29989077,922000008,CDXL,13.62,0.393,20201003CDLG000510025125,2020-05-03,09:02
3409,29999817,930000201,CDXL,11.52,1.000,20201003CDLG000510025125,2020-05-04,09:02
3410,30202566,930020001,CDXL,9.52,1.000,20201003CDLG000510025125,2020-05-05,09:02
3411,30000984,930020600,CDXL,6.52,1.000,20201003CDLG000510025125,2020-05-06,09:02
3412,30204927,930020600,CDXL,1.90,1.000,20201003CDLG000510025125,2020-05-07,09:02
3413,30214313,930020502,CDXL,8.52,1.000,20201003CDLG000510025125,2020-05-08,09:02
3414,30044266,912000103,CDXL,12.62,0.577,20201003CDLG000510025125,2020-05-09,09:02
3415,30203553,930020600,CDXL,4.82,1.000,20201003CDLG000510025125,2020-05-10,09:02
3416,29989077,922000008,CDXL,13.61,0.479,20201003CDLG000510025126,2020-05-11,09:03
3417,29989072,922000002,CDXL,0.78,1.026,20201003CDLG000510025126,2020-05-12,09:03
3418,29989059,922000003,CDXL,1.98,1.162,20201003CDLG000510025126,2020-05-13,09:03
3419,29989059,922000003,CDXL,1.98,1.263,20201003CDLG000510025126,2020-05-14,09:03
3420,30146019,913040000,CDXL,11.72,1.000,20201003CDLG000510025127,2020-05-15,09:03
3421,30114875,924000000,CDXL,25.61,0.754,20201003CDLG000510025128,2020-05-16,09:06
3422,30214817,925090000,CDXL,39.43,0.564,20201003CDLG000510025130,2020-05-17,09:08
3423,29989105,922000000,CDXL,2.80,0.692,20201003CDLG000510025130,2020-05-18,09:08
3424,29989071,922000002,CDXL,3.40,0.344,20201003CDLG000510025130,2020-05-19,09:08
3425,29989538,924020002,CDXL,12.62,0.277,20201003CDLG000510025130,2020-05-20,09:08
3426,30214815,925090000,CDXL,35.45,0.434,20201003CDLG000510025130,2020-05-21,09:08
3427,29989061,922000000,CDXL,5.57,0.084,20201003CDLG000510025130,2020-05-22,09:08
3428,30203548,912020107,CDXL,10.62,1.000,20201003CDLG000510025131,2020-05-23,09:09
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3431,29989072,922000002,CDXL,0.78,0.513,20201003CDLG000510025135,2020-05-26,09:18
3432,29989073,922000002,CDXL,4.80,0.309,20201003CDLG000510025135,2020-05-27,09:18
3433,30006332,915030305,CDXL,9.78,0.512,20201003CDLG000510025135,2020-05-28,09:18
3434,30214817,925090000,CDXL,39.42,0.412,20201003CDLG000510025135,2020-05-29,09:18
3435,30006329,915030303,CDXL,13.57,0.344,20201003CDLG000510025135,2020-05-30,09:18
3436,29989099,922000008,CDXL,1.58,0.570,20201003CDLG000510025135,2020-05-31,09:18

### ⑩第二种，用比较函数'gt''lt'和'&':

In [15]:
data[(data['日期'].lt(pd.Timestamp(e_date)))&(data['日期'].gt(pd.Timestamp(s_date)))]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
3406,30026255,915030104,CDXL,4.00,20.000,20201003CDLG000510025122,2020-05-01,08:58
3407,29989072,922000002,CDXL,0.78,0.769,20201003CDLG000510025123,2020-05-02,09:01
3408,29989077,922000008,CDXL,13.62,0.393,20201003CDLG000510025125,2020-05-03,09:02
3409,29999817,930000201,CDXL,11.52,1.000,20201003CDLG000510025125,2020-05-04,09:02
3410,30202566,930020001,CDXL,9.52,1.000,20201003CDLG000510025125,2020-05-05,09:02
3411,30000984,930020600,CDXL,6.52,1.000,20201003CDLG000510025125,2020-05-06,09:02
3412,30204927,930020600,CDXL,1.90,1.000,20201003CDLG000510025125,2020-05-07,09:02
3413,30214313,930020502,CDXL,8.52,1.000,20201003CDLG000510025125,2020-05-08,09:02
3414,30044266,912000103,CDXL,12.62,0.577,20201003CDLG000510025125,2020-05-09,09:02
3415,30203553,930020600,CDXL,4.82,1.000,20201003CDLG000510025125,2020-05-10,09:02
3416,29989077,922000008,CDXL,13.61,0.479,20201003CDLG000510025126,2020-05-11,09:03
3417,29989072,922000002,CDXL,0.78,1.026,20201003CDLG000510025126,2020-05-12,09:03
3418,29989059,922000003,CDXL,1.98,1.162,20201003CDLG000510025126,2020-05-13,09:03
3419,29989059,922000003,CDXL,1.98,1.263,20201003CDLG000510025126,2020-05-14,09:03
3420,30146019,913040000,CDXL,11.72,1.000,20201003CDLG000510025127,2020-05-15,09:03
3421,30114875,924000000,CDXL,25.61,0.754,20201003CDLG000510025128,2020-05-16,09:06
3422,30214817,925090000,CDXL,39.43,0.564,20201003CDLG000510025130,2020-05-17,09:08
3423,29989105,922000000,CDXL,2.80,0.692,20201003CDLG000510025130,2020-05-18,09:08
3424,29989071,922000002,CDXL,3.40,0.344,20201003CDLG000510025130,2020-05-19,09:08
3425,29989538,924020002,CDXL,12.62,0.277,20201003CDLG000510025130,2020-05-20,09:08
3426,30214815,925090000,CDXL,35.45,0.434,20201003CDLG000510025130,2020-05-21,09:08
3427,29989061,922000000,CDXL,5.57,0.084,20201003CDLG000510025130,2020-05-22,09:08
3428,30203548,912020107,CDXL,10.62,1.000,20201003CDLG000510025131,2020-05-23,09:09
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3431,29989072,922000002,CDXL,0.78,0.513,20201003CDLG000510025135,2020-05-26,09:18
3432,29989073,922000002,CDXL,4.80,0.309,20201003CDLG000510025135,2020-05-27,09:18
3433,30006332,915030305,CDXL,9.78,0.512,20201003CDLG000510025135,2020-05-28,09:18
3434,30214817,925090000,CDXL,39.42,0.412,20201003CDLG000510025135,2020-05-29,09:18
3435,30006329,915030303,CDXL,13.57,0.344,20201003CDLG000510025135,2020-05-30,09:18
3436,29989099,922000008,CDXL,1.58,0.570,20201003CDLG000510025135,2020-05-31,09:18

### ⑪第三种，用apply函数实现:

In [16]:
id_a=data.日期.apply(lambda x: x.year ==2020  and x.month==5)
data[id_a]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
3406,30026255,915030104,CDXL,4.00,20.000,20201003CDLG000510025122,2020-05-01,08:58
3407,29989072,922000002,CDXL,0.78,0.769,20201003CDLG000510025123,2020-05-02,09:01
3408,29989077,922000008,CDXL,13.62,0.393,20201003CDLG000510025125,2020-05-03,09:02
3409,29999817,930000201,CDXL,11.52,1.000,20201003CDLG000510025125,2020-05-04,09:02
3410,30202566,930020001,CDXL,9.52,1.000,20201003CDLG000510025125,2020-05-05,09:02
3411,30000984,930020600,CDXL,6.52,1.000,20201003CDLG000510025125,2020-05-06,09:02
3412,30204927,930020600,CDXL,1.90,1.000,20201003CDLG000510025125,2020-05-07,09:02
3413,30214313,930020502,CDXL,8.52,1.000,20201003CDLG000510025125,2020-05-08,09:02
3414,30044266,912000103,CDXL,12.62,0.577,20201003CDLG000510025125,2020-05-09,09:02
3415,30203553,930020600,CDXL,4.82,1.000,20201003CDLG000510025125,2020-05-10,09:02
3416,29989077,922000008,CDXL,13.61,0.479,20201003CDLG000510025126,2020-05-11,09:03
3417,29989072,922000002,CDXL,0.78,1.026,20201003CDLG000510025126,2020-05-12,09:03
3418,29989059,922000003,CDXL,1.98,1.162,20201003CDLG000510025126,2020-05-13,09:03
3419,29989059,922000003,CDXL,1.98,1.263,20201003CDLG000510025126,2020-05-14,09:03
3420,30146019,913040000,CDXL,11.72,1.000,20201003CDLG000510025127,2020-05-15,09:03
3421,30114875,924000000,CDXL,25.61,0.754,20201003CDLG000510025128,2020-05-16,09:06
3422,30214817,925090000,CDXL,39.43,0.564,20201003CDLG000510025130,2020-05-17,09:08
3423,29989105,922000000,CDXL,2.80,0.692,20201003CDLG000510025130,2020-05-18,09:08
3424,29989071,922000002,CDXL,3.40,0.344,20201003CDLG000510025130,2020-05-19,09:08
3425,29989538,924020002,CDXL,12.62,0.277,20201003CDLG000510025130,2020-05-20,09:08
3426,30214815,925090000,CDXL,35.45,0.434,20201003CDLG000510025130,2020-05-21,09:08
3427,29989061,922000000,CDXL,5.57,0.084,20201003CDLG000510025130,2020-05-22,09:08
3428,30203548,912020107,CDXL,10.62,1.000,20201003CDLG000510025131,2020-05-23,09:09
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3431,29989072,922000002,CDXL,0.78,0.513,20201003CDLG000510025135,2020-05-26,09:18
3432,29989073,922000002,CDXL,4.80,0.309,20201003CDLG000510025135,2020-05-27,09:18
3433,30006332,915030305,CDXL,9.78,0.512,20201003CDLG000510025135,2020-05-28,09:18
3434,30214817,925090000,CDXL,39.42,0.412,20201003CDLG000510025135,2020-05-29,09:18
3435,30006329,915030303,CDXL,13.57,0.344,20201003CDLG000510025135,2020-05-30,09:18
3436,29989099,922000008,CDXL,1.58,0.570,20201003CDLG000510025135,2020-05-31,09:18

### ⑫第四种，用between函数实现:

In [17]:
id_b=data.日期.between(pd.Timestamp(s_date),pd.Timestamp(e_date))
data[id_b]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
3405,29989059,922000003,CDXL,1.98,1.414,20201003CDLG000510025121,2020-04-30,08:35
3406,30026255,915030104,CDXL,4.00,20.000,20201003CDLG000510025122,2020-05-01,08:58
3407,29989072,922000002,CDXL,0.78,0.769,20201003CDLG000510025123,2020-05-02,09:01
3408,29989077,922000008,CDXL,13.62,0.393,20201003CDLG000510025125,2020-05-03,09:02
3409,29999817,930000201,CDXL,11.52,1.000,20201003CDLG000510025125,2020-05-04,09:02
3410,30202566,930020001,CDXL,9.52,1.000,20201003CDLG000510025125,2020-05-05,09:02
3411,30000984,930020600,CDXL,6.52,1.000,20201003CDLG000510025125,2020-05-06,09:02
3412,30204927,930020600,CDXL,1.90,1.000,20201003CDLG000510025125,2020-05-07,09:02
3413,30214313,930020502,CDXL,8.52,1.000,20201003CDLG000510025125,2020-05-08,09:02
3414,30044266,912000103,CDXL,12.62,0.577,20201003CDLG000510025125,2020-05-09,09:02
3415,30203553,930020600,CDXL,4.82,1.000,20201003CDLG000510025125,2020-05-10,09:02
3416,29989077,922000008,CDXL,13.61,0.479,20201003CDLG000510025126,2020-05-11,09:03
3417,29989072,922000002,CDXL,0.78,1.026,20201003CDLG000510025126,2020-05-12,09:03
3418,29989059,922000003,CDXL,1.98,1.162,20201003CDLG000510025126,2020-05-13,09:03
3419,29989059,922000003,CDXL,1.98,1.263,20201003CDLG000510025126,2020-05-14,09:03
3420,30146019,913040000,CDXL,11.72,1.000,20201003CDLG000510025127,2020-05-15,09:03
3421,30114875,924000000,CDXL,25.61,0.754,20201003CDLG000510025128,2020-05-16,09:06
3422,30214817,925090000,CDXL,39.43,0.564,20201003CDLG000510025130,2020-05-17,09:08
3423,29989105,922000000,CDXL,2.80,0.692,20201003CDLG000510025130,2020-05-18,09:08
3424,29989071,922000002,CDXL,3.40,0.344,20201003CDLG000510025130,2020-05-19,09:08
3425,29989538,924020002,CDXL,12.62,0.277,20201003CDLG000510025130,2020-05-20,09:08
3426,30214815,925090000,CDXL,35.45,0.434,20201003CDLG000510025130,2020-05-21,09:08
3427,29989061,922000000,CDXL,5.57,0.084,20201003CDLG000510025130,2020-05-22,09:08
3428,30203548,912020107,CDXL,10.62,1.000,20201003CDLG000510025131,2020-05-23,09:09
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3430,30007867,910000000,CDXL,6.62,5.000,20201003CDLG000510025133,2020-05-25,09:15
3431,29989072,922000002,CDXL,0.78,0.513,20201003CDLG000510025135,2020-05-26,09:18
3432,29989073,922000002,CDXL,4.80,0.309,20201003CDLG000510025135,2020-05-27,09:18
3433,30006332,915030305,CDXL,9.78,0.512,20201003CDLG000510025135,2020-05-28,09:18
3434,30214817,925090000,CDXL,39.42,0.412,20201003CDLG000510025135,2020-05-29,09:18
3435,30006329,915030303,CDXL,13.57,0.344,20201003CDLG000510025135,2020-05-30,09:18
3436,29989099,922000008,CDXL,1.58,0.570,20201003CDLG000510025135,2020-05-31,09:18
3437,30020103,915030301,CDXL,9.60,0.481,20201003CDLG000510025135,2020-06-01,09:18

## 6.筛选“类别ID”包含'000'的数据
### ⑬第一种，用contains函数：

In [18]:
data['类别ID']=data['类别ID'].values.astype('str')#砖混为字符串
id_c=data.类别ID.str.contains('000',na=False)
data[id_c]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
0,30006206,915000003,CDNL,25.23,0.328,20201003CDLG000210052759,2011-01-03,09:56
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
2,30200518,922000000,CDNL,19.62,0.230,20201003CDLG000210052759,2011-01-05,09:56
3,29989105,922000000,CDNL,2.80,2.044,20201003CDLG000210052759,2011-01-06,09:56
4,30179558,915000100,CDNL,47.41,0.226,20201003CDLG000210052759,2011-01-07,09:56
...,...,...,...,...,...,...,...,...
3470,30023041,923000006,CDXL,3.20,1.620,20201003CDLG000510025146,2020-07-04,10:58
3471,30038941,911010002,CDXL,17.62,1.000,20201003CDLG000510025146,2020-07-05,10:58
3475,30033854,910000000,CDXL,9.62,1.000,20201003CDLG000510025149,2020-07-09,11:17
3476,30206214,910000000,CDXL,15.62,1.000,20201003CDLG000510025150,2020-07-10,11:40
3477,30129510,925090000,CDXL,23.21,0.312,20201003CDLG000510025151,2020-07-11,11:50

### ⑭第二种，用isin函数：

In [19]:
id_i=data.类别ID.isin(['000'])  #接受一个列表
data[id_i]
# 很遗憾，isin函数搞不定，因为它只能判断该列中元素是否在列表中

Empty DataFrame
Columns: [商品ID, 类别ID, 门店编号, 单价, 销量, 订单ID, 日期, 时间]
Index: []

## 7.筛选商品ID以“301”开头的运营数据
### ⑮需要用contains函数结合正则表达式使用：

In [20]:
data['商品ID']=data['商品ID'].values.astype('str')  #将该列转换为字符数据类型
id_c2=data.商品ID.str.contains('301\d{5}',na=False)
data[id_c2]

,商品ID,类别ID,门店编号,单价,销量,订单ID,日期,时间
1,30163281,914010000,CDNL,2.00,2.000,20201003CDLG000210052759,2011-01-04,09:56
4,30179558,915000100,CDNL,47.41,0.226,20201003CDLG000210052759,2011-01-07,09:56
6,30179520,915000100,CDNL,77.52,0.086,20201003CDLG000210052759,2011-01-09,09:56
7,30184351,915000106,CDNL,15.57,0.420,20201003CDLG000210052759,2011-01-10,09:56
8,30184351,915000106,CDNL,15.58,0.470,20201003CDLG000210052759,2011-01-11,09:56
...,...,...,...,...,...,...,...,...
3429,30135547,930000201,CDXL,9.52,7.000,20201003CDLG000510025132,2020-05-24,09:12
3448,30143065,911010100,CDXL,29.42,1.000,20201003CDLG000510025138,2020-06-12,09:37
3450,30173850,920090000,CDXL,10.62,0.782,20201003CDLG000510025138,2020-06-14,09:37
3457,30174841,923000008,CDXL,6.80,0.919,20201003CDLG000510025140,2020-06-21,09:41
3477,30129510,925090000,CDXL,23.21,0.312,20201003CDLG000510025151,2020-07-11,11:50